name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./
      run: cargo build --verbose
# TODO add back when subsystem test doesn't hang forever      
#    - name: Run tests
#      run: cargo test --verbose
